### PR TITLE
Update igls.py

### PR DESCRIPTION
**Pull request by falex69**
correct a call for the table in def start()

### CODE REVIEW

**Comment by femtotrader** [comment]
Thanks for this fix.

Are you able to get IG live stream now ?

**Comment by falex69** [comment]
Hi.

It's my pleasure. Your igls module is very usefull for python STREAM client.

I've never had this pb in the past because I always use 'silent=False' when creating a Table ... so I never catch this code error, before reading the module code deeply.

This morning, I've try 'silent=true' when creating a table, and do a 'client.start(myTable)' just after :
The start function is called, the with statement is done but IG never start the stream. 
I've try with the epic price Offer/Bid for several epic such as EURUSD or DAX or GBPUSD and no-one start the stream.

If I create my table with 'silent=false' (as default) then no pb the stream start at the next tick ...

So there is still a pb but I'm not aware of LS technology so where ? I don't know.

Florian

----- Mail original -----
De: "femtotrader" <notifications@github.com>
À: "femtotrader/ig-markets-stream-api-python-library" <ig-markets-stream-api-python-library@noreply.github.com>
Cc: "falex69" <falex@free.fr>
Envoyé: Vendredi 29 Mai 2015 09:16:55
Objet: Re: [ig-markets-stream-api-python-library] Update igls.py (#1)



Thanks for this fix. 

Are you able to get IG live stream now ?

**Comment by femtotrader** [comment]
Thanks Florian but igls.py is not my work but

https://github.com/dw/py-lightstreamer/blob/master/lightstreamer.py

Unfortunately I don't know LS technology enough to help

I think we should make a more object orient approach for this IG stream API library.

Like I previously did for REST API https://github.com/femtotrader/ig-markets-rest-api-python-library/

Any idea about API design ?

Femto

**Comment by falex69** [comment]
Ok

Will you report the "correction" to the source or do I ?

No, when I've got question about the API I write a message to the IG community at http://labs.ig.com

----- Mail original -----
De: "femtotrader" <notifications@github.com>
À: "femtotrader/ig-markets-stream-api-python-library" <ig-markets-stream-api-python-library@noreply.github.com>
Cc: "falex69" <falex@free.fr>
Envoyé: Vendredi 29 Mai 2015 10:53:12
Objet: Re: [ig-markets-stream-api-python-library] Update igls.py (#1)



Thanks Florian but igls.py is not my work but 

https://github.com/dw/py-lightstreamer/blob/master/lightstreamer.py 

Unfortunately I don't know LS technology enough to help 

I think we should make a more object orient approach for this IG stream API library. 

Like I previously did for REST API https://github.com/femtotrader/ig-markets-rest-api-python-library/ 

Any idea about API design ? 

Femto

**Comment by femtotrader** [comment]
It was ever fixed upstream. I don't know why my version was buggy.

**Pull request merged**
